engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  sass-lint:
    enabled: true
  scss-lint:
    enabled: true
  remark-lint:
    enabled: true
