language: ruby
sudo: required
dist: trusty

env:
  - CXX=g++-4.8 RAILS_GROUPS=build

addons:
  postgresql: "13.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  bundler: true
  directories:
    - node_modules
    - client/node_modules
    - client/apps/hello_world/node_modules

branches:
  only:
  - master
  - staging
  - stable

services:
  - postgresql

before_install:
  - cp config/secrets.yml.example config/secrets.yml
  - cp config/ci.database.yml config/database.yml
  - cp .env.example .env
  - nvm install 14.18.2
  - nvm use 14.18.2
  - npm install -g yarn

install:
  - bundle install --path vendor/bundle
  - yarn

before_script:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - bundle exec rails db:create
  - bundle exec rails db:schema:load

script:
  - ./bin/ci
  - yarn test
