# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
Defaults: &defaults

  admin_name: Administrator
  admin_email: admin@example.com
  admin_password: changeme

  encryption_key: '<Run rake secret to get a value to put here>'

  # Main application settings
  application_name: "LTI Starter App"
  application_main_domain: <%= %Q{#{ENV["APP_SUBDOMAIN"]}.#{ENV["APP_ROOT_DOMAIN"] || "lvh.me"}} %>

  # Email Settings
  application_root_domain: <%= ENV["APP_ROOT_DOMAIN"] || "ltistarterapp.com" %>
  email_provider_username: admin@example.com
  email_provider_password: changeme

  # Assets (webpack server in dev mode)
  assets_url: <%= ENV["ASSETS_URL"] || "http://localhost:8080" %>

  canvas_url:  <%= ENV["APP_DEFAULT_CANVAS_URL"] %>
  # Obtain a Canvas Developer ID and Key for the from an Account Admin for
  # the instance of Canvas to install the app into. ID and Keys are specific
  # to a Canvas instance (they are not global like they used to be).
  # This key and secret is used for the OAuth dance with Canvas
  canvas_developer_id: <%= ENV["CANVAS_DEVELOPER_ID"] %>
  canvas_developer_key: <%= ENV["CANVAS_DEVELOPER_KEY"] %>

  auth0_client_id: lti_starter_app
  auth0_client_secret: '<Run rake secret to get a value to put here>'

development:
  <<: *defaults

  hello_world_lti_secret: '<Run rake secret to get a value to put here>'
  admin_lti_secret: '<Run rake secret to get a value to put here>'

  secret_key_base: '<Run rake secret to get a value to put here>'

test:
  <<: *defaults

  secret_key_base: '<Run rake secret to get a value to put here>'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *defaults

  hello_world_lti_secret: '<Run rake secret to get a value to put here>'
  admin_lti_secret: '<Run rake secret to get a value to put here>'

  application_main_domain: <%= "#{ENV['APP_SUBDOMAIN']}.herokuapp.com" %>

  lti_launch_domain: ltistarterapp.com

  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  canvas_url: 'https://canvas.instructure.com'

  encryption_key: '<Run rake secret to get a value to put here>'
