name: brakeman

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '*'

jobs:
  brakeman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
      - name: Security audit application code
        run: bin/brakeman -q -w2
